---
title: "Untitled"
author: "IO"
date: "2022-12-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
```

# 

```{r}
ui <- fluidPage(
  selectInput("dataset", label = "Dataset", choices = ls("package:datasets")),
  verbatimTextOutput("summary"),
  tableOutput("table")
)

server <- function(input, output, session) {
  
  output$summary <- renderPrint({
    dataset <- get(input$dataset, "package:datasets")
    summary(dataset)
  })
  
  output$table <- renderTable({
    dataset <- get(input$dataset, "package:datasets")
    dataset
  })
}

shinyApp(ui, server)
```

Yukarıdaki kodda `package::datasets` iki kere yazılmış. Bu aslında kötü bir uygulama ve debugging kısmında sorunlara yol açabilir. Bunu yerine tekrarlanan ifadeyi `reactive()` kalıbının içine alabiliriz. 

```{r}
ui <- fluidPage(
  selectInput("dataset", label = "Dataset123", choices = ls("package:datasets")),
  verbatimTextOutput("summary"),
  tableOutput("table")
)

server <- function(input, output, session) {
  # Create a reactive expression
  dataset <- reactive({
    get(input$dataset, "package:datasets")
  })

  output$summary <- renderPrint({
    # Use a reactive expression by calling it like a function
    summary(dataset())
  })
  
  output$table <- renderTable({
    dataset()
  })
}

shinyApp(ui, server)
```



```{r}
library(shiny)

ui <- fluidPage(
  
textInput("name", "What's your name?"),
textOutput("greeting")

)

server <- function(input, output, session) {
  output$greeting <- renderText({
  paste0("Hello ", input$name)
})
}

shinyApp(ui, server)
```

```{r}
library(shiny)

ui <- fluidPage(
  sliderInput("x", label = "If x is", min = 1, max = 50, value = 30),
  sliderInput("y", label = "If y is", min = 1, max = 50, value = 30),
  "then x times y is",
  textOutput("product")
)

server <- function(input, output, session) {
  output$product <- renderText({ 
    input$x * input$y
  })
}

shinyApp(ui, server)
```

```{r}
library(shiny)

ui <- fluidPage(
  sliderInput("x", "If x is", min = 1, max = 50, value = 30),
  sliderInput("y", "and y is", min = 1, max = 50, value = 5),
  "then, (x * y) is", textOutput("product"),
  "and, (x * y) + 5 is", textOutput("product_plus5"),
  "and (x * y) + 10 is", textOutput("product_plus10")
)

server <- function(input, output, session) {

  product <- reactive({
      get(input$x * input$y)
    })
  
  output$product <- renderText({ 
    product
  })
  output$product_plus5 <- renderText({ 
    product + 5
  })
  output$product_plus10 <- renderText({ 
    product + 10
  })
}

shinyApp(ui, server)
```

